modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="lord_of_warden"
version="1.0.0"
displayName="lord of warden"
displayURL="https://modrinth.com/user/Entropy777"
credits="Entropy"
authors="Entropy"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.lord_of_warden]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration